services:
  redis:
    image: redis:latest
    container_name: redis_orchestrater
    ports:
      - "6380:6379"

  fastapi:
    build: .
    container_name: copilot_orchestrator
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
